version: '3'

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"    
    volumes:
      - redis_data:/var/lib/redis
  db:
    image: postgres:10.12-alpine
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}      
  app:
    build:
      context: .
    env_file:
      - ./.env
    entrypoint: ./entrypoint.app.sh
    volumes:
      - .:/cbv
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    entrypoint: ./entrypoint.celery.worker.sh
    volumes:
      - .:/cbv
    depends_on:
      - db
      - redis
      - app
volumes:
  data-db:
    driver: local
  redis_data:
networks:
  default: