version: '3'

services:
  redis:
    image: redis:alpine
  db:
    image: postgres:10.12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}      
  app:
    build:
      context: .
    env_file:
      - ./.env
    entrypoint: ./entrypoint.app.sh
    volumes:
      - .:/cbv
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    restart: always
    build:
      context: .
    entrypoint: ./entrypoint.celery.worker.sh
    volumes:
      - .:/cbv
    depends_on:
      - db
      - app
      - redis