version: '3'

services:
  web:
    container_name: "django"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cbv
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: "psdb"
    image: postgres:10.12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
