version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"    
  db:
    image: postgres:10.12-alpine
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}      
  app:
    build:
      context: .
    env_file:
      - ./.env
    entrypoint: ./entrypoint.app.sh
    volumes:
      - .:/cbv
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    restart: always
    build:
      context: .
    entrypoint: ./entrypoint.celery.worker.sh
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379}
    volumes:
      - .:/cbv
    depends_on:
      - db
      - app
      - redis
volumes:
  data-db:
    driver: local