# Generated by Django 3.2.9 on 2021-11-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
