# Generated by Django 3.2.9 on 2021-11-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField()),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
