# Generated by Django 3.2.9 on 2021-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverpage',
            field=models.FileField(null=True, upload_to='coverpage/'),
        ),
    ]
