# Generated by Django 3.2.9 on 2021-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_coverpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
