# Generated by Django 3.2.9 on 2021-11-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_coverpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(null=True, upload_to='coverpage/'),
        ),
    ]
