# Generated by Django 3.2.9 on 2021-11-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_coverpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-id',)},
        ),
    ]
